### ISSUE TITLE
Zbytečné TGMPA?

### ISSUE THREAD

**Issue by jakubboucek** [redbitcz/simpleshop-wp-plugin#11]
Zkoumáním kódu jsem došel k závěru, že komponenta [TGMPA](http://tgmpluginactivation.com/), který [je součástí pluginu](https://github.com/redbitcz/simpleshop-wp-plugin/blob/b44ae40c58ce5cb9061abfc4001e69009abe6fd1/composer.json#L20), není účelně využíván a měl by tedy být odstraněn.

Prosím @vasikgreif o prověření mojí teorie, zda se zakládá na správné úvaze.

## Odůvodnění
- Plugin je využíván [pouze pro instalaci `rest-api`](https://github.com/redbitcz/simpleshop-wp-plugin/blob/b44ae40c58ce5cb9061abfc4001e69009abe6fd1/src/Loader.php#L101), které je však od 
WordPressu verze 4.7 přímo součástí WP core.
- V pluginu samotném však není `rest-api` využíváno, protože pro připojení k SimpleShop API je využíván cURL.
- V novějších verzích pluginu, kde se už s využitím modernějšího přístupu k API počítá, ale současně už neplánuji podporu extrémně zastaralých verzí, což `< 4.7` [rozhodně je](https://wordpress.org/about/roadmap/).
- S dalším vývojem pluginu navrhuji tedy zaříznout podporu WP `< 4.7` a tento plugin odstranit.

**Comment by vasikgreif** [comment]
Vyřešeno v #38
