### ISSUE TITLE
Umožnit zrušení automatického přesměrování, pokud uživatel nemá práva na sekci

### ISSUE THREAD

**Issue by vlastimilott** [redbitcz/simpleshop-wp-plugin#19]
Potřebovali bychom odkrývat článek postupně a máme toto řešení hotové - jde o existují rozsáhlý magazín, takže úprava pomocí shortcodů není možná.
Jediné, co nám komplikuje situaci, je automatické přesměrování, pokud uživatel není přihlášený nebo nemá do sekce přístup. Potřebujeme, aby se na detailu článku objevil náš designový formulář, ne aby se uživatel dostal na nějakou obecnou stránku.

Navrhl bych úpravu v objektu Access a jeho konstruktoru, přidat filtr:
```
$redirect = true;
if (apply_filters('ssc_redirect_on_locked_content', $redirect) == true) {
 add_action( 'template_redirect', [ $this, 'check_access' ] );
}
```

Díky za reakci, jestli je to pro vás akceptovatelné. @jakubboucek

**Comment by jakubboucek** [comment]
@vlastimilott Díky za podnět, z mého pohledu to vypadá rozumně, předám dál.

@vasikgreif Prosím koukněte na návrh @vlastimilott, zda dává smysl z pohledu architektury pluginu.

**Comment by vasikgreif** [comment]
Dobrý den, dává smysl a ničemu nevadí, přidáno.
